initial commit
kelvinndmo/teziafrica-be pull request #15
Opened 2021-05-02 23:31 UTC by nicholas-oduor

2021-05-03 12:19 UTC, kelvinndmo requested changes

2021-05-03 12:19 UTC, kelvinndmo commented on authentication/permissions.py
> +        client = request.user.user_type ==2
What is the need of this @nicholas-oduor , since there are customers, clients and admins, this permission class is redundant, please remove it

2021-05-03 14:36 UTC, nicholas-oduor commented
i have removed it and created the permissions in the utils folder


On Mon, May 3, 2021 at 3:20 PM Novak ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In authentication/permissions.py
> <https://github.com/kelvinndmo/teziafrica-be/pull/15#discussion_r625046521>
> :
>
> > +             super().has_permission(request, view)
> +             and (admin)
> +            )
> +class IsClientOrAdmin(BasePermission):
> +    def has_permission(self, request, view):
> +        client = request.user.user_type ==2
> +        admin = request.user.user_type ==3
> +        return bool(
> +             super().has_permission(request, view)
> +             and (client or admin)
> +            )
> +
> +class IsCustomerOrClientOrAdmin(BasePermission):
> +    def has_permission(self, request, view):
> +        customer = request.user.user_type ==1
> +        client = request.user.user_type ==2
>
> What is the need of this @nicholas-oduor
> <https://github.com/nicholas-oduor> , since there are customers, clients
> and admins, this permission class is redundant, please remove it
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kelvinndmo/teziafrica-be/pull/15#pullrequestreview-650298391>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARZVAD3AJE5NNHDGWVRWZYDTL2IHXANCNFSM4374HIKA>
> .
>

2021-05-05 07:20 UTC, devsamuelmwangi commented
## **Kindly switch the base branch from `_master_` to `_develop_`. **

2021-05-05 07:48 UTC, closed without merging